### ISSUE TITLE
[Question] Which are your configurations?

### ISSUE THREAD

**Issue by Relwi** [MM2-0/fdroid#1]
Well, I'm trying to do my own F-Droid repo, following this tutorial: https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

But I have problems with it, it doesn't work for me, so my questions are:

1. Are you using `nginx` like in the tutorial or are you using other one?
2. I need to open some ports to make it work in the `F-Droid` app? (or `Droid-ify`)
3. You have some fundamental configuration in your config file? Like some config for security or good architecture, idk
4. If I upload some apps that aren't mine could I get in trouble? (like Steam, Discord, etc...)

Thank you very much!

**Comment by MM2-0** [comment]
> Are you using nginx like in the tutorial or are you using other one?

I use Github for hosting. All the APK files are in this repo. I take advantage of the fact that Github is serving all repository contents as static files.

Basically, `fdroid init` and `fdroid update` create a directury structure like this:

```
metadata /
repo /
  - [package_name] /
  - [package_name]_[release_code].apk
  - index-v1.jar
  - index-v1.json
  - index.css
  - index.html
  - index.jar
  - index.xml
tmp /
config.yml
```

You need a webserver that is able to serve static files (like nginx) and configure it to serve only the `repo/` folder (which is also what you find in this Git repo).

> I need to open some ports to make it work in the F-Droid app? (or Droid-ify)

Just the standard ports (80 for http or 443 for https if you configure nginx to use https)

> You have some fundamental configuration in your config file? Like some config for security or good architecture, idk

Only the basic things, most of them are auto generated by `fdroid init`, I think:

```yaml
# see https://gitlab.com/fdroid/fdroidserver/blob/2.0.1/examples/config.yml
sdk_path: /path/to/android/sdk
apksigner: /path/to/apksigner/apksigner
keystore: keystore.p12
keystorepass: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
keypass: xxxxxxxxxxxxxxxxxxxxxxxxxx
repo_keyalias: xxxxxxxxxxxxxxxx
keydname: CN=xxxxxxxxxxxx, OU=F-Droid
repo_url: https://https://raw.githubusercontent.com/MM2-0/fdroid/main/fdroid/repo/?fingerprint=156FBAB952F6996415F198F3F29628D24B30E725B0F07A2B49C3A9B5161EEE1A
repo_name: MM20 Apps
repo_description: Apps developed and distributed by MM20
repo_icon: icon.png

```

> If I upload some apps that aren't mine could I get in trouble? (like Steam, Discord, etc...)

Depends on the app's license. If it's FOSS, you can do whatever you want. For proprietary apps, you are probably not allowed to re-distribute them, unless their license terms state otherwise.
